@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
class Star  {
    -Name: string
    -Luminosity: double
    -Mass: long
    -Volume: double
    -Age: int
    +Star(Name: string, Luminosity: double, Mass: long, Volume: double, Age: int)
    +Star()
    +getName():string
    +setName(string)
    +getLuminosity():double
    +setLuminosity(double)
    +getMass():double
    +setMass(long)
    +getVolume():double
    +setVolume(double)
    +getAge():int
    +setAge(int)
    +toString():string
}

@enduml