@startuml
'https://plantuml.com/class-diagram

class Player{
    -Modello: String
    -Marca: String
    -Playlist: playlist
    +getModello(): String
    +setModello(String)
    +getMarca:(String)
    +setMarca(String)
    +play()
    +succesivo()
    +precedente()
    +SlezionaBrano(int n)
}

class Brano{
    -Titolo: String
    -Autore: String
    +getTitolo:(String)
    +setTitolo(String)
    +getAutore:(String)
    +setAutore(String)
}

class Playlist{
    -Titolo: String
    -Brani[]: Brano
    +getTitolo:(String)
    +setTitolo(String)
}


@enduml