@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
class Rettangolo{
    -latoMaggiore: int
    -latoMinore: int
    +getlatoMaggiote():int
    +setlatoMaggiore(int)
    +getlatoMinore():int
    +setlatoMinore(int)
    +Rettangolo()
    +Rettangolo(latoMaggiore,latoMinore)
    +getArea():int
    +getPerimetro():int
    +getDiagonale():int
    +toString():string
}
@enduml